Data:
  startFile: ./data/myBoundary/Pouch/pouch_start_new.ply
  secondFile: ./data/myBoundary/Pouch/pouch_second_new.ply
  dirichletVertices: [8, 9, 152, 278, 279]
  
Output:
  outputFilePrefix: ""
  outputFolder: ./output
  timestampOutput: True

numSteps: 32

TPE:
  Type: Scary
  alpha: 6
  beta: 12
  innerWeight: 1.e-5
  theta: 0.5
  thetaNear: 10.
  useAdaptivity: False

Energy:
  bendingWeight: 1.e-3
  elasticWeight: 10.
  tpeWeight: 1.
  barycenterWeight: 1.
  dirichletWeight: 1

# BoundaryTPE:
#   enabled: true
#   weight: 1.e-5
#   useInObjective: true
#   alpha: 6
#   beta: 12

Optimization:
  maxNumIterations: 100
  minStepsize: 1.e-12
  maxStepsize: 10.

