Data:  
  startFile: ./data/myBoundary/TwoSquares/ab_start.ply
  endFile: ./data/myBoundary/TwoSquares/ab_end.ply
  initFile: ./data/myBoundary/TwoSquares/ab_init_mid.ply
  dirichletVertices: [25, 29, 45, 49]
  
  # startFile: ./data/myBoundary/TwoSquares_n16/ab_start.ply
  # endFile: ./data/myBoundary/TwoSquares_n16/ab_end.ply
  # initFile: ./data/myBoundary/TwoSquares_n16/ab_init_mid.ply
  # dirichletVertices: [289, 305, 561, 577] 

  decimationFactor: -1.

Output:
  outputFilePrefix: ""
  outputFolder: ./output
  timestampOutput: True

  saveIntermediate: True
  intermediateEvery: 100
  intermediateFolder: intermediate

numSteps: 8
numLevels: 1

TPE:
  Type: Scary
  alpha: 6
  beta: 12
  innerWeight: 1.e-10
  theta: 0.5
  thetaNear: 2.
  useLowerSSMTerm: False
  useHigherSSMTerm: False
  useAdaptivity: False

Energy:
  bendingWeight: 1.e-3
  elasticWeight: 1.
  tpeWeight: 1
  dirichletWeight: 1.e-2
  barycenterWeight: 1.e-2

Boundary:
  inspect: false
  saveVisualization: false 

BoundaryTPE:
  enabled: true
  weight: 1.0e-5
  useInObjective: true
  alpha: 6
  beta: 12
  checkGradient: false

Optimization:
  Type: TrustRegion
  Preconditioner: ElasticHessianAndReducedHessian

  maxNumIterations: 200
  minStepsize: 1.e-12
  maxStepsize: 10.
  minReduction: 1.e-7